// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public partial class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line 3 "x:\dir\subdir\Test\TestComponent.cshtml"
 __o = DateTime.Now;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "x:\dir\subdir\Test\TestComponent.cshtml"
 for (var i = 0; i < 10; i++)
{
    

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "x:\dir\subdir\Test\TestComponent.cshtml"
  __o = i;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "x:\dir\subdir\Test\TestComponent.cshtml"
             
}

#line default
#line hidden
#nullable disable
#nullable restore
#line 14 "x:\dir\subdir\Test\TestComponent.cshtml"
  System.Console.WriteLine(1);System.Console.WriteLine(2);

#line default
#line hidden
#nullable disable
#nullable restore
#line 18 "x:\dir\subdir\Test\TestComponent.cshtml"
__o = JsonToHtml(@"{
  'key1': 'value1'
}");

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 23 "x:\dir\subdir\Test\TestComponent.cshtml"
       
    [Parameter]
    public int IncrementAmount { get; set; } = 3;

    public static string JsonToHtml(string json)
    {
        return $"<pre>{json}</pre>";
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
